FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

# Copy all projects
COPY . .

# Restore and build
RUN dotnet restore CustomerApi/CustomerApi.csproj
RUN dotnet restore CustomerApi.Tests/CustomerApi.Tests.csproj

# Run tests
CMD ["dotnet", "test", "CustomerApi.Tests/CustomerApi.Tests.csproj", "--verbosity", "normal"]
